- name: Update APT Cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  ignore_errors: true # This is because of issues with the MPR package repo
- name: Global Utility Installation
  ansible.builtin.apt:
    pkg: "{{ system_packages }}"
  tags: apt
- name: Server Specific Utility Installation
  ansible.builtin.apt:
    pkg: "{{ global_system_server_packages | default('[]') }}"
  when: global_system_server_packages != []
- name: Figurine Installation
  ansible.builtin.copy:
    src: figurine
    dest: /usr/local/bin/figurine
    mode: '0755'

- name: CheckMK Agent Installation
  when: global_system_checkmk_install
  block:
    - name: CheckMK Agent | Copy Installation Media
      ansible.builtin.copy:
        src: check-mk-agent_2.3.0p30-1_all.deb
        dest: /tmp
    - name: CheckMK Agent | Install Agent
      ansible.builtin.apt:
        deb: /tmp/check-mk-agent_2.3.0p30-1_all.deb
        state: present
