packages:
  - git
  - neofetch
  - stress
  - fio
  - gnupg
  - curl
  - ca-certificates
  - unzip
  - htop
  - git
  - net-tools
  - nfs-common
  - cifs-utils
  - rsync
  - tmux
  - ansible-lint
  - sl
  - tree
  - gh
  - xclip

ssh_config:
  - "Host *"
  - "   StrictHostKeyChecking no"
