monitor_groups:
  - name: Servers
    description: Servers
  - name: Network Infrastructure
    description: Networking Devices
  - name: Web Services
    description: Web Based Services
  - name: Database Services
    description: Database Servers
