system_packages:
  - cron
  - htop
  - neofetch
  - git
  - nfs-common
  - net-tools
  - dnsutils
  - rsync
  - tmux
  - rsyslog
  - unzip
  - ca-certificates
  - curl
  - gnupg
  - fio
  - inxi
  - smartmontools
  - acl
