motd:
  - regexp: "Server Function:"
    line: "Server Function: {{ function }}"
  - regexp: "Server Type:"
    line: "Server Type: {{ server_type }}"
  - regexp: "Server Location:"
    line: "Server Location: {{ site_name }}"
