- name: Ansible Installation
  block:
    - name: Ensure system is up-to-date
      ansible.builtin.apt:
        update_cache: true
    - name: Add Ansible PPA repository
      ansible.builtin.apt_repository:
        repo: 'ppa:ansible/ansible'
        state: present
    - name: Install Ansible
      ansible.builtin.apt:
        pkg:
          - software-properties-common
          - ansible
          - python3-passlib
        state: present
- name: Install Ansible Collections
  community.general.ansible_galaxy_install:
    type: collection
    name: "{{ item }}"
    force: true
  with_items:
    - lucasheld.uptime_kuma
    - azure.azcollection
  become: true
  become_user: ci
- name: Install Pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true
- name: Install Azure Dependancies
  ansible.builtin.pip:
    requirements: /home/ci/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt
    break_system_packages: true
  become: true
