- name: Bind Package Installation
  become: true
  ansible.builtin.apt:
    pkg: bind9
- name: UFW Firewall Configuration
  community.general.ufw:
    rule: allow
    port: '53'
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"
- name: Install Prerequisits on Ansible Host
  ansible.builtin.apt:
    pkg: python3-dnspython
  become: true
  delegate_to: localhost
- name: Create BIND log directory
  ansible.builtin.file:
    path: "{{ bind_logging.path }}"
    state: directory
    owner: bind
    group: bind
    mode: '0755'
  become: true
- name: Create Log File
  ansible.builtin.file:
    path: "{{ bind_logging.path }}/{{ bind_logging.file }}"
    mode: '0644'
    owner: bind
    group: bind
    state: touch
  become: true
- name: Build Configuration File
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ bind_general.path }}/named.conf"
    owner: root
    group: bind
    mode: '0644'
  become: true
  notify: Config Change
- name: Check for Zone Files
  ansible.builtin.stat:
    path: "{{ bind_general.path }}/{{ item }}.zone"
  with_items: "{{ bind_zones }}"
  register: zone_check
- name: Build Zone Files (Initial Install Only)
  ansible.builtin.template:
    src: "zone.j2"
    dest: "{{ bind_general.path }}/{{ item }}.zone"
    owner: root
    group: bind
    mode: '0644'
  with_items: "{{ zone_check.results }}"
  become: true
  notify: Zone Change
  when: not item.stat.exists
