- name: Allow sudo without password
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ base.username }}"
    line: "{{ base.username }} ALL=(ALL) NOPASSWD:ALL"
    create: true
    mode: '0644'
- name: Utility Installation
  become: true
  tags: apt
  ansible.builtin.apt:
    pkg: "{{ item }}"
  with_items: "{{ packages }}"
- name: SSH - Add Trusted Hosts
  ansible.builtin.known_hosts:
    host: "{{ item.name }}"
    key: "{{ item.ssh_host }}"
  with_items: "{{ vault.ssh.trusted_hosts }}"
  when: base.configure_known_hosts
  no_log: true
- name: Copy home directory files
  ansible.builtin.copy:
    src: home/
    dest: ~/
    mode: '0755'
- name: Copy Executables
  ansible.builtin.copy:
    src: bin/
    dest: ~/bin/
    mode: '0755'
- name: Set Git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ base.git_name }}"
- name: Set Git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ base.git_email }}"
- name: Create Git Directory
  ansible.builtin.file:
    path: "{{ repository_directory }}"
    state: directory
    mode: '0755'
