username: null
runner_name: null
runner_labels: null
runner_path: "/etc/act_runner"
runner_url: https://gitea.com/gitea/act_runner/releases/download/v0.2.11/act_runner-0.2.11-linux-amd64
gitea_instance: null
gitea_token: null
gitea_aws:
  aws_secret_access_key: null
  aws_access_key_id: null
  endpoint_url: null
