galaxy_info:
  author: Dan Shaw
  description: Ansible role to install CheckMK and perform basic configuration.
  min_ansible_version: "2.1"
  license: GPL
  galaxy_tags: []
dependencies: [
  letsencrypt
]
