enable_packages: true
enable_ssh_config: true
enable_ufw_config: true
enable_env_config: true
enable_motd_config: true
enable_syslog_config: true
global_system_server_function: changeme
global_system_server_type: changeme
global_system_server_location: changeme
global_system_server_deployment_type: changeme
global_system_server_packages: []
global_system_nfs: null
