name: Docker Installation
on:
  workflow_dispatch:
  push:
    paths:
      - roles/docker/**
  schedule:
    - cron: "01 04 * * *"
jobs:
  terraform:
    uses: epichouse/workflow-templates/.github/workflows/ansible-role.yaml@main
    with:
        rolepath: "../${{ github.event.repository.name }}/roles/docker"
        rolehosts: "docker"
        multisite: true
    secrets:
        sudo_password: ${{secrets.SUDO_PASSWORD}}
        mastertoken: ${{secrets.MASTERTOKEN}}