name: Nagios Installation
on:
  workflow_dispatch:
  repository_dispatch: 
    types: [nagios]

jobs:
  terraform:
    uses: epichouse/workflow-templates/.github/workflows/ansible-role.yaml@main
    with:
        rolepath: "../${{ github.event.repository.name }}/roles/nagios"
        rolehosts: "nagios"
        multisite: true
    secrets:
        sudo_password: ${{secrets.SUDO_PASSWORD}}
        mastertoken: ${{secrets.MASTERTOKEN}}
        vault_password: ${{secrets.VAULT_PASSWORD}}